export const SAVE_USER_BEGIN = "SAVE_USER_BEGIN";
export const SAVE_USER_COMPLETE = "SAVE_USER_COMPLETE";
export const SAVE_USER_ERROR = "SAVE_USER_ERROR";


export const CREATE_USER_FETCHING = "CREATE_USER_FETCHING";
export const CREATE_USER_COMPLETE = "CREATE_USER_COMPLETE";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER= "DELETE_USER";
export const LOAD_USERS = "LOAD_USERS";
