export const SAVE_USER_PENDING = "SAVE_USER_PENDING";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_ERROR = "SAVE_USER_ERROR";
export const UNLOAD_SAVED_USER = "UNLOAD_SAVED_USER";

export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const LOAD_USER_PENDING = "LOAD_USER_PENDING";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const UNLOAD_USER = "UNLOAD_USER";

export const LOAD_USERS_PENDING = "LOAD_USERS_PENDING";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const LOAD_USER_PROFILE_PENDING = "LOAD_USER_PROFILE_PENDING";
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const LOAD_USER_PROFILE_ERROR = "LOAD_USER_PROFILE_ERROR";

export const AUTH_USER_PENDING = 'AUTH_USER_PENDING';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';

export const LOAD_INSTITUTIONS_PENDING = "LOAD_INSTITUTIONS_PENDING";
export const LOAD_INSTITUTIONS_SUCCESS = "LOAD_INSTITUTIONS_SUCCESS";
export const LOAD_INSTITUTIONS_ERROR = "LOAD_INSTITUTIONS_ERROR";

export const DELETE_INSTITUTION_PENDING = "DELETE_INSTITUTION_PENDING";
export const DELETE_INSTITUTION_SUCCESS = "DELETE_INSTITUTION_SUCCESS";
export const DELETE_INSTITUTION_ERROR = "DELETE_INSTITUTION_ERROR";

export const LOAD_INSTITUTION_PENDING = "LOAD_INSTITUTION_PENDING";
export const LOAD_INSTITUTION_SUCCESS = "LOAD_INSTITUTION_SUCCESS";
export const LOAD_INSTITUTION_ERROR = "LOAD_INSTITUTION_ERROR";
export const UNLOAD_INSTITUTION = "UNLOAD_INSTITUTION";

export const SAVE_INSTITUTION_PENDING = "SAVE_INSTITUTION_PENDING";
export const SAVE_INSTITUTION_SUCCESS = "SAVE_INSTITUTION_SUCCESS";
export const SAVE_INSTITUTION_ERROR = "SAVE_INSTITUTION_ERROR";
export const UNLOAD_SAVED_INSTITUTION = "UNLOAD_SAVED_INSTITUTION";

export const LOAD_INSTITUTION_MEMBERS_PENDING = "LOAD_INSTITUTION_MEMBERS_PENDING";
export const LOAD_INSTITUTION_MEMBERS_SUCCESS = "LOAD_INSTITUTION_MEMBERS_SUCCESS";
export const LOAD_INSTITUTION_MEMBERS_ERROR = "LOAD_INSTITUTION_MEMBERS_ERROR";
export const UNLOAD_INSTITUTION_MEMBERS = "UNLOAD_INSTITUTION_MEMBERS";

export const DELETE_RECORD_PENDING = "DELETE_RECORD_PENDING";
export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS";
export const DELETE_RECORD_ERROR = "DELETE_RECORD_ERROR";

export const LOAD_RECORDS_PENDING = "LOAD_RECORDS_PENDING";
export const LOAD_RECORDS_SUCCESS = "LOAD_RECORDS_SUCCESS";
export const LOAD_RECORDS_ERROR = "LOAD_RECORDS_ERROR";

export const LOAD_RECORD_PENDING = "LOAD_RECORD_PENDING";
export const LOAD_RECORD_SUCCESS = "LOAD_RECORD_SUCCESS";
export const LOAD_RECORD_ERROR = "LOAD_RECORD_ERROR";
export const UNLOAD_RECORD = "UNLOAD_RECORD";

export const LOAD_FORMGEN_PENDING = "LOAD_FORMGEN_PENDING";
export const LOAD_FORMGEN_SUCCESS = "LOAD_FORMGEN_SUCCESS";
export const LOAD_FORMGEN_ERROR = "LOAD_FORMGEN_ERROR";

export const SAVE_RECORD_PENDING = "SAVE_RECORD_PENDING";
export const SAVE_RECORD_SUCCESS = "SAVE_RECORD_SUCCESS";
export const SAVE_RECORD_ERROR = "SAVE_RECORD_ERROR";
export const UNLOAD_SAVED_RECORD = "UNLOAD_SAVED_RECORD";

export const SET_TRANSITION_PAYLOAD = "SET_TRANSITION_PAYLOAD";
export const SET_VIEW_HANDLERS = "SET_VIEW_HANDLERS";

export const PASSWORD_CHANGE_PENDING = "PASSWORD_CHANGE_PENDING";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_ERROR = "PASSWORD_CHANGE_ERROR";

export const GENERATE_USERNAME_PENDING = "GENERATE_USERNAME_PENDING";
export const GENERATE_USERNAME_SUCCESS = "GENERATE_USERNAME_SUCCESS";

export const PASSWORD_RESET_PENDING = "PASSWORD_RESET_PENDING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";

export const LOAD_ACTIONS_HISTORY_PENDING = "LOAD_ACTIONS_HISTORY_PENDING";
export const LOAD_ACTIONS_HISTORY_SUCCESS = "LOAD_ACTIONS_HISTORY_SUCCESS";
export const LOAD_ACTIONS_HISTORY_ERROR = "LOAD_ACTIONS_HISTORY_ERROR";

export const LOAD_ACTION_HISTORY_PENDING = "LOAD_ACTION_HISTORY_PENDING";
export const LOAD_ACTION_HISTORY_SUCCESS = "LOAD_ACTION_HISTORY_SUCCESS";
export const LOAD_ACTION_HISTORY_ERROR = "LOAD_ACTION_HISTORY_ERROR";
export const UNLOAD_ACTION_HISTORY = "UNLOAD_ACTION_HISTORY";

export const LOAD_STATISTICS_PENDING = "LOAD_STATISTICS_PENDING";
export const LOAD_STATISTICS_SUCCESS = "LOAD_STATISTICS_SUCCESS";
export const LOAD_STATISTICS_ERROR = "LOAD_STATISTICS_ERROR";

export const VALIDATE_TOKEN_PENDING = "VALIDATE_TOKEN_PENDING";
export const VALIDATE_TOKEN_SUCCESS = "VALIDATE_TOKEN_SUCCESS";
export const VALIDATE_TOKEN_ERROR = "VALIDATE_TOKEN_ERROR";

export const PASSWORD_CHANGE_TOKEN_PENDING = "PASSWORD_CHANGE_TOKEN_PENDING";
export const PASSWORD_CHANGE_TOKEN_SUCCESS = "PASSWORD_CHANGE_TOKEN_SUCCESS";
export const PASSWORD_CHANGE_TOKEN_ERROR = "PASSWORD_CHANGE_TOKEN_ERROR";

export const SEND_INVITATION_PENDING = "SEND_INVITATION_PENDING";
export const SEND_INVITATION_SUCCESS = "SEND_INVITATION_SUCCESS";
export const SEND_INVITATION_ERROR = "SEND_INVITATION_ERROR";

export const INVITATION_OPTION_DELETE_PENDING = "INVITATION_OPTION_DELETE_PENDING";
export const INVITATION_OPTION_DELETE_SUCCESS = "INVITATION_OPTION_DELETE_SUCCESS";
export const INVITATION_OPTION_DELETE_ERROR = "INVITATION_OPTION_DELETE_ERROR";

export const IMPERSONATE_PENDING = "IMPERSONATE_PENDING";
export const IMPERSONATE_SUCCESS = "IMPERSONATE_SUCCESS";
export const IMPERSONATE_ERROR = "IMPERSONATE_ERROR";