export const SAVE_USER_PENDING = "SAVE_USER_PENDING";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_ERROR = "SAVE_USER_ERROR";

export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const LOAD_USER_PENDING = "LOAD_USER_PENDING";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const UNLOAD_USER = "UNLOAD_USER";

export const LOAD_USERS_PENDING = "LOAD_USERS_PENDING";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const LOAD_USER_PROFILE_PENDING = "LOAD_USER_PROFILE_PENDING";
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const LOAD_USER_PROFILE_ERROR = "LOAD_USER_PROFILE_ERROR";

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';
